# Generated by Django 5.0.6 on 2024-10-31 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_login_login_date_remove_login_login_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='signup_datetime',
        ),
        migrations.AddField(
            model_name='student',
            name='signup_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='signup_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
