# Generated by Django 5.0.6 on 2025-05-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_codesnippet_user_student_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(default='profile.png', upload_to=''),
        ),
    ]
