# Generated by Django 5.0.6 on 2024-11-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_student_signup_datetime_student_signup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password1',
            field=models.CharField(max_length=60),
        ),
    ]
