# Generated by Django 5.0.6 on 2024-11-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_login_password1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password1',
            new_name='password',
        ),
    ]
