# Generated by Django 5.0.6 on 2024-11-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_password1_login_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
