# Generated by Django 5.0.6 on 2024-11-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_login_login_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password1',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='password2',
            field=models.CharField(max_length=128),
        ),
    ]
